### ISSUE TITLE
How install it ?

### ISSUE THREAD

**Issue by felipesalomao** [MestreLion/legendastv#1]
Oi, como instalar ? roda no PC, NAS ? Vlw

**Comment by felipesalomao** [comment]
Opa, não tinha recebido notificação do tópico.. Passei aqui novamente para ver se tinha novidade. Segue meu skype: felipesalomao2
Só falta integrar baixar legendas automaticamente para o servidor ficar perfeito.. Só as legendas do legendas.tv são boas e nem o sickbeard e o couchpotato suportam o site pois são baseados no subliminal que não tem o legendas.tv na lista de provedores por precisar de login e senha (nada que um user/pass hardcoded não resolveria).. Vc me ajudando, vou tentar fazer um tutorial para a turma do sickbeard/couchpotato (muitos).. Abs e parabéns pelo projeto.

**Comment by marcoaleixo** [comment]
Cara, tô tentando usar mas tô achando bem confuso esse processo de instalar.
Clonei o seu repositorio, tô rodando no python 2.7 : python legendas.tv /home/usuario/dir/filmes/
Entendi errado como funciona?

**Comment by MestreLion** [comment]
Talvez falte baixar alguma dependência, o arquivo de LOG em `~/.cache/legendastv/legendastv.log` deve dar uma luz sobre o que deu errado.

Pode também estar faltando preencher seu login e senha do site Legendas.TV no arquivo de configuração em `~/.config/legendastv/legendastv.cfg`

Qualquer dúvida é só perguntar!

**Comment by marcoaleixo** [comment]
Recebi esse erro:

```
"Traceback (most recent call last):
  File "legendastv.py", line 50, in <module>
    from legendastv import g, filetools, subtitles, utils
  File "/home/marco/legendas/legendastv/legendastv/__init__.py", line 23, in <module>
    from . import g
  File "/home/marco/legendas/legendastv/legendastv/g.py", line 27, in <module>
    import xdg.BaseDirectory as xdg
  File "/home/marco/miniconda2/lib/python2.7/site-packages/xdg.py", line 40
    def _getenv(variable: str, default: str) -> str:
                        ^
SyntaxError: invalid syntax
```
"
Tô rodando no python 2.7

**Comment by MestreLion** [comment]
Estranho, esse erro foi não foi no meu sistema, e sim no módulo `xdg`. E foi um erro de sintaxe ainda por cima. De onde você o baixou? O esperado pelo meu sistema é o mesmo utilizado pelo Debian/Ubuntu no pacote `python-xdg`

**Comment by marcoaleixo** [comment]
De onde eu baixei o que?
O seu sistema eu dei git-clone, o python-xdg não lembro de ter usado em nenhum outro lugar.

**Comment by marcoaleixo** [comment]
Posso rodar dentro de um env do conda, né?
