### ISSUE TITLE
How to run in a headless server (command-line, no display)? Como rodar em linha de comando?

### ISSUE THREAD

**Issue by cassioac** [MestreLion/legendastv#20]
Estou tentando rodar na linha de comando por ssh, mas está dando este erro:

root@plex:/videos/seriados/Life After Top Chef# legendastv Life.After.Top.Chef.S01E01.720p.HDTV.x264-2HD.mkv 
Traceback (most recent call last):
  File "/root/.local/bin/legendastv", line 132, in <module>
    utils.notify("ERROR! Check log for details")
  File "/opt/legendastv/legendastv/utils.py", line 48, in notify
    _bus_obj  = dbus.SessionBus().get_object(_bus_name, _bus_path)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

É um servidor, não tem X11... 

Ele precisa de interface gráfica pra rodar?

Abs

Cassio

**Comment by cassioac** [comment]
Executei o export DISPLAY=:0 e mudou um pouco o erro...

root@plex:/videos/seriados/Life After Top Chef# legendastv Life.After.Top.Chef.S01E01.720p.HDTV.x264-2HD.mkv 
Traceback (most recent call last):
  File "/root/.local/bin/legendastv", line 132, in <module>
    utils.notify("ERROR! Check log for details")
  File "/opt/legendastv/legendastv/utils.py", line 48, in notify
    _bus_obj  = dbus.SessionBus().get_object(_bus_name, _bus_path)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: //bin/dbus-launch terminated abnormally with the following error: Autolaunch error: X11 initialization failed.

abs

Casio

**Comment by MestreLion** [comment]
Não *precisa* de interface gráfica pre rodar, mas por default ele exibe balões de notificação no Ubuntu/Gnome3, e essas notificações exigem tanto DBUS (que nao funciona direito como `root`) quanto X11.

No seu caso, pra rodar num servidor sem interface gráfica, tem que desabilitar as notificações. Você pode fazer isso pelo arquivo `legendastv.ini`: é só mudar a linha `notifications = True` pra `notifications = False`

Qualquer outra duvida, erro ou sugestão, nao hesite em reportar aqui ou entrar em contato!
Abraços!

**Comment by MestreLion** [comment]
Me avise se a configuração funcionar pra eu fechar o bug

**Comment by cassioac** [comment]
Worked like a charm, thanks!
