### ISSUE TITLE
Novo erro

### ISSUE THREAD

**Issue by cassioac** [MestreLion/legendastv#22]
Atualizei o script, ta rodando bem melhor agora, mas tem algum arquivo zoando quando passo ele na pasta inteira, como faço para descobrir qual é?

eis o erro:

root@plex:/# legendastv /videos
2016-01-05 23:43:39,898 NOTIFY   ERROR! Check log for details
2016-01-05 23:43:39,945 CRITICAL 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
Traceback (most recent call last):
  File "/root/.local/bin/legendastv", line 128, in <module>
    main(sys.argv[1:])
  File "/root/.local/bin/legendastv", line 97, in main
    for root, _, files in os.walk(filename):
  File "/usr/lib/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)

EDIT: Isso só acontece na pasta de filmes, na pasta de seriados roda normal...

tkz

Cassio

**Comment by MestreLion** [comment]
É algum arquivo com caracteres inválidos (ou seja, não-UTF-8), provavelmente baixados/copiados via Windows (que as vezes salvar nomes de arquivos com outros encodings). Fiz uma atualização no programa pra logar exatamente quais arquivos dão erro (assim vc pode identificar e renomear), alem de pular eles e continuar com os outros sem dar problema. Me avisa se ficou tudo certo agora!
